"""
Generate web-optimized WebP versions of the SPMS conference photos and a typed
manifest for the gallery page.

For every original under static/photos/day{N}/ it emits:
  static/gallery/thumb/day{N}/{id}.webp   (long edge 600px,  q72) - grid
  static/gallery/large/day{N}/{id}.webp   (long edge 2560px, q82) - lightbox + download
and writes src/lib/data/galleryPhotos.ts (large-image dimensions per photo).

Originals stay untracked / out of git. Idempotent: existing outputs are skipped,
so the script can be safely interrupted and re-run.
"""

import os
import json
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "static", "photos")
OUT_DIR = os.path.join(ROOT, "static", "gallery")
MANIFEST_TS = os.path.join(ROOT, "src", "lib", "data", "galleryPhotos.ts")

THUMB_EDGE = 600
LARGE_EDGE = 2560
THUMB_Q = 72
LARGE_Q = 82

VALID_EXT = (".jpg", ".jpeg", ".png")


def _resize_long_edge(img, edge):
    w, h = img.size
    if max(w, h) <= edge:
        return img  # never upscale
    if w >= h:
        nw, nh = edge, round(h * edge / w)
    else:
        nw, nh = round(w * edge / h), edge
    return img.resize((nw, nh), Image.LANCZOS)


def process_one(task):
    day, src_path, photo_id = task
    thumb_path = os.path.join(OUT_DIR, "thumb", f"day{day}", photo_id + ".webp")
    large_path = os.path.join(OUT_DIR, "large", f"day{day}", photo_id + ".webp")

    try:
        with Image.open(src_path) as im:
            im = ImageOps.exif_transpose(im)  # honor camera/phone rotation
            im = im.convert("RGB")

            large = _resize_long_edge(im, LARGE_EDGE)
            lw, lh = large.size
            if not os.path.exists(large_path):
                large.save(large_path, "WEBP", quality=LARGE_Q, method=6)

            if not os.path.exists(thumb_path):
                thumb = _resize_long_edge(large, THUMB_EDGE)
                thumb.save(thumb_path, "WEBP", quality=THUMB_Q, method=6)

        return {"day": day, "id": photo_id, "w": lw, "h": lh}
    except Exception as e:  # noqa: BLE001 - report and keep going
        return {"day": day, "id": photo_id, "error": str(e)}


def collect_tasks():
    tasks = []
    for entry in sorted(os.listdir(SRC_DIR)):
        if not entry.lower().startswith("day"):
            continue
        day_dir = os.path.join(SRC_DIR, entry)
        if not os.path.isdir(day_dir):
            continue
        day = int("".join(c for c in entry if c.isdigit()))
        for fname in sorted(os.listdir(day_dir)):
            if fname.lower().endswith(VALID_EXT):
                photo_id = os.path.splitext(fname)[0]
                tasks.append((day, os.path.join(day_dir, fname), photo_id))
    return tasks


def ensure_dirs(tasks):
    days = sorted({t[0] for t in tasks})
    for tier in ("thumb", "large"):
        for day in days:
            os.makedirs(os.path.join(OUT_DIR, tier, f"day{day}"), exist_ok=True)
    os.makedirs(os.path.dirname(MANIFEST_TS), exist_ok=True)


def write_manifest(results):
    ok = [r for r in results if "error" not in r]
    ok.sort(key=lambda r: (r["day"], r["id"]))
    lines = [
        "// AUTO-GENERATED by scripts/process_gallery.py - do not edit by hand.",
        "// Conference photos (SPMS Communications Team). Originals are kept out of git;",
        "// only the web-optimized WebP versions under static/gallery/ are committed.",
        "",
        "export interface GalleryPhoto {",
        "\t/** Conference day the photo was taken (1 = 9 Jun, 2 = 10 Jun, ...). */",
        "\tday: number;",
        "\t/** File stem; resolves to /gallery/{thumb,large}/day{day}/{id}.webp */",
        "\tid: string;",
        "\t/** Intrinsic width of the large (lightbox) image, in px. */",
        "\tw: number;",
        "\t/** Intrinsic height of the large (lightbox) image, in px. */",
        "\th: number;",
        "}",
        "",
        "export const galleryPhotos: GalleryPhoto[] = [",
    ]
    for r in ok:
        lines.append(
            f'\t{{ day: {r["day"]}, id: "{r["id"]}", w: {r["w"]}, h: {r["h"]} }},'
        )
    lines.append("];")
    lines.append("")
    with open(MANIFEST_TS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    tasks = collect_tasks()
    if not tasks:
        print("No source photos found under", SRC_DIR)
        return
    ensure_dirs(tasks)
    print(f"Processing {len(tasks)} photos -> {OUT_DIR}", flush=True)

    results = []
    done = 0
    workers = max(1, (os.cpu_count() or 4) - 1)
    with ProcessPoolExecutor(max_workers=workers) as ex:
        futs = [ex.submit(process_one, t) for t in tasks]
        for fut in as_completed(futs):
            r = fut.result()
            results.append(r)
            done += 1
            if "error" in r:
                print(f"  ERROR {r['id']}: {r['error']}", flush=True)
            if done % 25 == 0 or done == len(tasks):
                print(f"  {done}/{len(tasks)} done", flush=True)

    write_manifest(results)
    errors = [r for r in results if "error" in r]
    print(
        f"Done. {len(results) - len(errors)} ok, {len(errors)} errors. "
        f"Manifest: {MANIFEST_TS}",
        flush=True,
    )
    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
